/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AppBtn: typeof import('./src/components/button/AppBtn.vue')['default']
    AppBtnTooltip: typeof import('./src/components/button/AppBtnTooltip.vue')['default']
    AppCard: typeof import('./src/components/card/AppCard.vue')['default']
    AppDialog: typeof import('./src/components/dialog/AppDialog.vue')['default']
    AppDialogCard: typeof import('./src/components/dialog/AppDialogCard.vue')['default']
    AppFooter: typeof import('./src/components/page/AppFooter.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    AppSpinner: typeof import('./src/components/loading/AppSpinner.vue')['default']
    AppText: typeof import('./src/components/text/AppText.vue')['default']
    CircularBtn: typeof import('./src/components/utils/circularBtn.vue')['default']
    FooterBar: typeof import('./src/components/utils/FooterBar.vue')['default']
    GalleryCarouselDialog: typeof import('./src/views/GalleryCarouselDialog.vue')['default']
    GalleryView: typeof import('./src/views/GalleryView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MediaView: typeof import('./src/views/MediaView.vue')['default']
    NavigationBar: typeof import('./src/components/utils/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwingingNineView: typeof import('./src/views/SwingingNineView.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
